version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "isi-bible-verse-image-sender"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-139cq5tfaxqkk"
s3_prefix = "isi-bible-verse-image-sender"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
